name: 'Github Actions'
on: 
  push:
    branches:
      - "main"
  pull_request:
    branches: ["main"]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run pack
      - run: npm run fix
      - run: npm run test-cjs
      - run: npm run test-cjs-default
      - run: npm run test-cjs-min
      - run: npm run test-cjs-min-default
      - run: npm run test-esm
      - run: npm run test-esm-default
      - run: npm run test-esm-min
      - run: npm run test-esm-min-default
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
